// deno-lint-ignore-file ban-unused-ignore no-explicit-any no-empty-interface
///////////////////////////////////
// !!! DO NOT EDIT THIS FILE !!! //
///////////////////////////////////

import type { SlackAPIResponse } from "../response";
export type CallsAddResponse = SlackAPIResponse & {
  ok: boolean;
  error?: string;
  needed?: string;
  provided?: string;
  warning?: string;
  call?: Call;
  response_metadata?: ResponseMetadata;
};

export interface Call {
  id?: string;
  date_start?: number;
  date_end?: number;
  external_unique_id?: string;
  join_url?: string;
  desktop_app_join_url?: string;
  external_display_id?: string;
  title?: string;
  channels?: string[];
  users?: User[];
}

export interface User {
  slack_id?: string;
  external_id?: string;
  display_name?: string;
  avatar_url?: string;
}

export interface ResponseMetadata {
  messages?: string[];
}
