// deno-lint-ignore-file ban-unused-ignore no-explicit-any no-empty-interface
///////////////////////////////////
// !!! DO NOT EDIT THIS FILE !!! //
///////////////////////////////////

import type { SlackAPIResponse } from "../response.ts";
export type WorkflowsFeaturedListResponse = SlackAPIResponse & {
  ok: boolean;
  error?: string;
  needed?: string;
  provided?: string;
  warning?: string;
  featured_workflows?: FeaturedWorkflow[];
  invalid_channel_ids?: string[];
  response_metadata?: ResponseMetadata;
};

export interface FeaturedWorkflow {
  channel_id?: string;
  triggers?: Trigger[];
}

export interface Trigger {
  id?: string;
  type?: string;
}

export interface ResponseMetadata {
  messages?: string[];
}
